### ISSUE TITLE
Pre-commit hook for pylic

### ISSUE THREAD

**Issue by afuetterer** [ubersan/pylic#111]
Hi,

thanks for the great package. Would it possible to offer a pre-commit hook for license checking?
I could be useful to run the license checking via pre-commit e.g. in CI, if someone added a new dependency, or a dependency changes its license.

Maybe like this?

`.pre-commit-hooks.yaml`:
```yaml
- id: pylic
  name: pylic
  entry: pylic check
  language: python
  pass_filenames: false
```
